Repository Azure/MachineLearningNotebooks, pull requests merged in 2020-09, with the labels that each got.

#1122 docs: Move unintended side columns below the main rows
  how-to-use-azureml/machine-learning-pipelines/intro-to-pipelines/aml-pipelines-data-transfer.ipynb
Labels: Pipelines, do-not-merge, review-team-triage

#1123 docs: bring docs in line with code
  how-to-use-azureml/machine-learning-pipelines/intro-to-pipelines/aml-pipelines-showcasing-datapath-and-pipelineparameter.ipynb
Labels: Pipelines, do-not-merge, review-team-triage

#1137 update samples from Release-64 as a part of SDK release
  how-to-use-azureml/automated-machine-learning/README.md
  how-to-use-azureml/automated-machine-learning/classification-text-dnn/auto-ml-classification-text-dnn.ipynb
  how-to-use-azureml/automated-machine-learning/classification-text-dnn/auto-ml-classification-text-dnn.yml
  how-to-use-azureml/automated-machine-learning/classification-text-dnn/helper.py
  how-to-use-azureml/automated-machine-learning/classification-text-dnn/infer.py
  how-to-use-azureml/machine-learning-pipelines/intro-to-pipelines/aml-pipelines-data-transfer.ipynb
  how-to-use-azureml/machine-learning-pipelines/intro-to-pipelines/aml-pipelines-showcasing-datapath-and-pipelineparameter.ipynb
  index.md
Labels: do-not-merge

#1148 update samples from Release-65 as a part of SDK release
  how-to-use-azureml/automated-machine-learning/README.md
  how-to-use-azureml/automated-machine-learning/classification-text-dnn/auto-ml-classification-text-dnn.ipynb
  how-to-use-azureml/automated-machine-learning/classification-text-dnn/auto-ml-classification-text-dnn.yml
  how-to-use-azureml/automated-machine-learning/classification-text-dnn/helper.py
  how-to-use-azureml/automated-machine-learning/classification-text-dnn/infer.py
  how-to-use-azureml/azure-databricks/automl/README.md
  how-to-use-azureml/azure-databricks/automl/automl-databricks-local-01.ipynb
  how-to-use-azureml/azure-databricks/automl/automl-databricks-local-with-deployment.ipynb
  index.md
Labels: do-not-merge, review-team-triage

#1157 update samples from Release-67 as a part of SDK release
  tutorials/regression-automl-nyc-taxi-data/regression-automated-ml.ipynb
Labels: do-not-merge, review-team-triage

#1158 update samples from Release-68 as a part of SDK release
  how-to-use-azureml/automated-machine-learning/README.md
  how-to-use-azureml/automated-machine-learning/classification-text-dnn/auto-ml-classification-text-dnn.ipynb
  how-to-use-azureml/automated-machine-learning/classification-text-dnn/auto-ml-classification-text-dnn.yml
  how-to-use-azureml/automated-machine-learning/classification-text-dnn/helper.py
  how-to-use-azureml/automated-machine-learning/classification-text-dnn/infer.py
  index.md
Labels: do-not-merge, review-team-triage

#1165 quickstart added
  tutorials/get-started-day1/IDE-users/01-create-workspace.py
  tutorials/get-started-day1/IDE-users/02-create-compute.py
  tutorials/get-started-day1/IDE-users/03-run-hello.py
  tutorials/get-started-day1/IDE-users/04-run-pytorch.py
  tutorials/get-started-day1/IDE-users/05-upload-data.py
  tutorials/get-started-day1/IDE-users/06-run-pytorch-data.py
  tutorials/get-started-day1/IDE-users/README.md
  tutorials/get-started-day1/IDE-users/environments/pytorch-env.yml
  tutorials/get-started-day1/IDE-users/src/hello.py
  tutorials/get-started-day1/IDE-users/src/model.py
  tutorials/get-started-day1/IDE-users/src/train.py
  tutorials/get-started-day1/code/hello/hello.py
  tutorials/get-started-day1/code/pytorch-cifar10-train-with-logging/model.py
  tutorials/get-started-day1/code/pytorch-cifar10-train-with-logging/train.py
  tutorials/get-started-day1/code/pytorch-cifar10-train/model.py
  tutorials/get-started-day1/code/pytorch-cifar10-train/train.py
  tutorials/get-started-day1/code/pytorch-cifar10-your-data/model.py
  tutorials/get-started-day1/code/pytorch-cifar10-your-data/train.py
  tutorials/get-started-day1/configuration/pytorch-aml-env.yml
  tutorials/get-started-day1/configuration/pytorch-env.yml
  tutorials/get-started-day1/day1-part1-setup.ipynb
  tutorials/get-started-day1/day1-part2-hello-world.ipynb
  tutorials/get-started-day1/day1-part3-train-model.ipynb
  tutorials/get-started-day1/day1-part4-data.ipynb
Labels: do-not-merge, review-team-triage

#1166 patch for resume training notebook
  how-to-use-azureml/ml-frameworks/tensorflow/train-tensorflow-resume-training/train-tensorflow-resume-training.ipynb
Labels: do-not-merge, review-team-triage
