Repository Azure/MachineLearningNotebooks, pull requests merged in 2022-03, with the labels that each got.

#1700 update samples from Release-123 as a part of SDK release
  configuration.ipynb
  contrib/RAPIDS/azure-ml-with-nvidia-rapids.ipynb
  contrib/fairness/fairlearn-azureml-mitigation.ipynb
  contrib/fairness/fairlearn-azureml-mitigation.yml
  contrib/fairness/upload-fairness-dashboard.ipynb
  contrib/fairness/upload-fairness-dashboard.yml
  how-to-use-azureml/automated-machine-learning/automl_env.yml
  how-to-use-azureml/automated-machine-learning/automl_env_linux.yml
  how-to-use-azureml/automated-machine-learning/automl_env_mac.yml
  how-to-use-azureml/automated-machine-learning/classification-bank-marketing-all-features/auto-ml-classification-bank-marketing-all-features.ipynb
  how-to-use-azureml/automated-machine-learning/classification-credit-card-fraud/auto-ml-classification-credit-card-fraud.ipynb
  how-to-use-azureml/automated-machine-learning/classification-text-dnn/auto-ml-classification-text-dnn.ipynb
  how-to-use-azureml/automated-machine-learning/continuous-retraining/auto-ml-continuous-retraining.ipynb
  how-to-use-azureml/automated-machine-learning/experimental/automl_thin_client_env.yml
  how-to-use-azureml/automated-machine-learning/experimental/automl_thin_client_env_mac.yml
  how-to-use-azureml/automated-machine-learning/experimental/classification-credit-card-fraud-local-managed/auto-ml-classification-credit-card-fraud-local-managed.ipynb
  how-to-use-azureml/automated-machine-learning/experimental/regression-model-proxy/auto-ml-regression-model-proxy.ipynb
  how-to-use-azureml/automated-machine-learning/forecasting-backtest-many-models/auto-ml-forecasting-backtest-many-models.ipynb
  how-to-use-azureml/automated-machine-learning/forecasting-backtest-single-model/auto-ml-forecasting-backtest-single-model.ipynb
  how-to-use-azureml/automated-machine-learning/forecasting-beer-remote/Beer_no_valid_split_test.csv
  how-to-use-azureml/automated-machine-learning/forecasting-beer-remote/Beer_no_valid_split_train.csv
  how-to-use-azureml/automated-machine-learning/forecasting-beer-remote/auto-ml-forecasting-beer-remote.yml
  how-to-use-azureml/automated-machine-learning/forecasting-bike-share/auto-ml-forecasting-bike-share.ipynb
  how-to-use-azureml/automated-machine-learning/forecasting-energy-demand/auto-ml-forecasting-energy-demand.ipynb
  how-to-use-azureml/automated-machine-learning/forecasting-forecast-function/auto-ml-forecasting-function.ipynb
  how-to-use-azureml/automated-machine-learning/forecasting-github-dau/auto-ml-forecasting-github-dau.ipynb
  how-to-use-azureml/automated-machine-learning/forecasting-github-dau/auto-ml-forecasting-github-dau.yml
  how-to-use-azureml/automated-machine-learning/forecasting-github-dau/github_dau_2011-2018_test.csv
  how-to-use-azureml/automated-machine-learning/forecasting-github-dau/github_dau_2011-2018_train.csv
  how-to-use-azureml/automated-machine-learning/forecasting-github-dau/helper.py
  how-to-use-azureml/automated-machine-learning/forecasting-github-dau/infer.py
  how-to-use-azureml/automated-machine-learning/forecasting-hierarchical-timeseries/auto-ml-forecasting-hierarchical-timeseries.ipynb
  how-to-use-azureml/automated-machine-learning/forecasting-many-models/auto-ml-forecasting-many-models.ipynb
  how-to-use-azureml/automated-machine-learning/forecasting-orange-juice-sales/auto-ml-forecasting-orange-juice-sales.ipynb
  how-to-use-azureml/automated-machine-learning/forecasting-recipes-univariate/auto-ml-forecasting-univariate-recipe-run-experiment.ipynb
  how-to-use-azureml/automated-machine-learning/forecasting-recipes-univariate/helper_functions.py
  how-to-use-azureml/automated-machine-learning/local-run-classification-credit-card-fraud/auto-ml-classification-credit-card-fraud-local.ipynb
  how-to-use-azureml/automated-machine-learning/regression-explanation-featurization/auto-ml-regression-explanation-featurization.ipynb
  how-to-use-azureml/automated-machine-learning/regression-explanation-featurization/score_explain.py
  how-to-use-azureml/automated-machine-learning/regression/auto-ml-regression.ipynb
  how-to-use-azureml/deployment/deploy-to-local/register-model-deploy-local-advanced.ipynb
  how-to-use-azureml/explain-model/azure-integration/gpu-explanation/train-explain-model-gpu-tree-explainer.ipynb
  how-to-use-azureml/explain-model/azure-integration/remote-explanation/explain-model-on-amlcompute.yml
  how-to-use-azureml/explain-model/azure-integration/run-history/save-retrieve-explanations-run-history.yml
  how-to-use-azureml/explain-model/azure-integration/scoring-time/train-explain-model-locally-and-deploy.ipynb
  how-to-use-azureml/explain-model/azure-integration/scoring-time/train-explain-model-locally-and-deploy.yml
  how-to-use-azureml/explain-model/azure-integration/scoring-time/train-explain-model-on-amlcompute-and-deploy.yml
  how-to-use-azureml/ml-frameworks/fastai/fastai-with-custom-docker/fastai-with-custom-docker.ipynb
  how-to-use-azureml/reinforcement-learning/cartpole-on-single-compute/cartpole_sc.ipynb
  how-to-use-azureml/reinforcement-learning/cartpole-on-single-compute/files/docker/Dockerfile
  how-to-use-azureml/responsible-ai/auto-ml-regression-responsibleai/auto-ml-regression-responsibleai.ipynb
  how-to-use-azureml/responsible-ai/visualize-upload-loan-decision/rai-loan-decision.yml
  how-to-use-azureml/track-and-monitor-experiments/logging-api/logging-api.ipynb
  index.md
  setup-environment/configuration.ipynb
  tutorials/compute-instance-quickstarts/quickstart-azureml-in-10mins/quickstart-azureml-in-10mins.ipynb
  tutorials/compute-instance-quickstarts/quickstart-azureml-python-sdk/quickstart-azureml-python-sdk.ipynb
  tutorials/image-classification-mnist-data/img-classification-part1-training.ipynb
Labels: do-not-merge

#1707 update samples from Release-124 as a part of SDK release
  how-to-use-azureml/automated-machine-learning/automl_env.yml
  how-to-use-azureml/automated-machine-learning/automl_env_linux.yml
  how-to-use-azureml/automated-machine-learning/automl_env_mac.yml
Labels: review-team-triage

#1711 update samples from Release-126 as a part of SDK release
  how-to-use-azureml/reinforcement-learning/cartpole-on-single-compute/files/docker/Dockerfile
Labels: do-not-merge

#1715 update samples from Release-127 as a part of SDK release
  how-to-use-azureml/automated-machine-learning/classification-text-dnn/auto-ml-classification-text-dnn.ipynb
  how-to-use-azureml/ml-frameworks/pytorch/train-hyperparameter-tune-deploy-with-pytorch/train-hyperparameter-tune-deploy-with-pytorch.yml
Labels: review-team-triage

#1720 update samples from Release-128 as a part of SDK release
  how-to-use-azureml/ml-frameworks/fastai/fastai-with-custom-docker/fastai-with-custom-docker.ipynb
Labels: do-not-merge

#1726 update samples from Release-131 as a part of SDK release
  how-to-use-azureml/automated-machine-learning/experimental/regression-model-proxy/auto-ml-regression-model-proxy.ipynb
Labels: do-not-merge, review-team-triage

#1729 add docker subfolder to pong notebook directly.
  how-to-use-azureml/reinforcement-learning/atari-on-distributed-compute/docker/Dockerfile-cpu
  how-to-use-azureml/reinforcement-learning/atari-on-distributed-compute/docker/Dockerfile-gpu
Labels: review-team-triage
